name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install toolchain
      run: rustup install stable && rustup install nightly
    - name: Install Bpflinker
      run: cargo install bpf-linker
    - name: Build ebpf
      run: cargo xtask build-ebpf
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
